### ISSUE TITLE
SVG badges are full white in Firefox

### ISSUE THREAD

**Issue by szekelymilan** [ellerbrock/open-source-badges#2]
Hello!
I have a big issue, the SVG badges are full white in Firefox. I tried to open them in Photoshop, but it shows a full white picture too.
In Chrome, IE, Edge, they're looking awesome. What can I do?
Screenshot: https://prnt.sc/ko68iy

Thanks!
Milan

**Comment by ellerbrock** [comment]
Hi @szekelymilan,

i think [this](https://github.com/ellerbrock/open-source-badges/pull/5) merged PR should fix it.

Thanks for mentioning!

**Comment by szekelymilan** [comment]
@ellerbrock It's still bad. 😕

**Comment by szekelymilan** [comment]
@ellerbrock It works well if I remove `<g mask="url(#m1)">`. Can you do a fix on it? 😃

**Comment by ellerbrock** [comment]
I merged your fix, thanks for the help!

**Comment by Rhitabrat** [comment]
The SVG image problem is not fixed yet. 

Please find firefox screenshot below.
[https://imgur.com/a/W4ig4l2]

I found this issue when working on another [repo](https://github.com/firstcontributions/first-contributions/blob/master/translations/README.np.md) that uses this repo's badges.

Screenshot: [https://imgur.com/a/hdSXyTa]
